/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logindulu;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author made
 */
public class login extends javax.swing.JFrame {
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordPass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbLevel = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        bdatabuku = new javax.swing.JButton();
        bdatapetugas = new javax.swing.JButton();
        bdatapeminjaman = new javax.swing.JButton();
        bdatapengembalian = new javax.swing.JButton();
        bdataanggota = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        Login = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username :");

        jLabel2.setText("Password :");

        jLabel3.setText("Level :");

        cmbLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Petugas", "Administrasi" }));

        jButton6.setText("Masuk");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Keluar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPasswordPass, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordUser)
                    .addComponent(cmbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addGap(45, 45, 45))
        );

        bdatabuku.setText("Data Buku");
        bdatabuku.setEnabled(false);
        bdatabuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdatabukuActionPerformed(evt);
            }
        });

        bdatapetugas.setText("Data Petugas");
        bdatapetugas.setEnabled(false);
        bdatapetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdatapetugasActionPerformed(evt);
            }
        });

        bdatapeminjaman.setText("Data Peminjaman");
        bdatapeminjaman.setEnabled(false);
        bdatapeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdatapeminjamanActionPerformed(evt);
            }
        });

        bdatapengembalian.setText("Data Pengembalian");
        bdatapengembalian.setEnabled(false);
        bdatapengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdatapengembalianActionPerformed(evt);
            }
        });

        bdataanggota.setText("Data Anggota");
        bdataanggota.setEnabled(false);
        bdataanggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdataanggotaActionPerformed(evt);
            }
        });

        menu.setText("Menu");

        Login.setSelected(true);
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        menu.add(Login);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Keluar");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        menu.add(jCheckBoxMenuItem1);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bdatapengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdatapeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdatabuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdataanggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdatapetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bdatapetugas)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(bdataanggota)
                        .addGap(47, 47, 47)
                        .addComponent(bdatabuku)
                        .addGap(42, 42, 42)
                        .addComponent(bdatapeminjaman)
                        .addGap(38, 38, 38)
                        .addComponent(bdatapengembalian)))
                .addGap(39, 39, 39))
            .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        try {
            Connection koneksi=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/db_perpustakaan","root","123");
            Statement stat= (Statement) koneksi.createStatement();
            ResultSet rs=stat.executeQuery("select * from tbl_petugas where nm_petugas='"+jPasswordUser.getText()+"' "
                    + "and password='"+jPasswordPass.getText()+"' and akses='"+cmbLevel.getSelectedItem()+"'" );
            rs.last();
            if(rs.getRow()>=1){
                    if(cmbLevel.getSelectedItem().equals("Admin")){
                    bdataanggota.setEnabled(true);
                    bdatabuku.setEnabled(true);
                    bdatapeminjaman.setEnabled(true);
                    bdatapetugas.setEnabled(true);
                    bdatapengembalian.setEnabled(true);
                    Login.setText("Logout");
                    PanelLogin.setVisible(false);
                    jPasswordPass.setText("");
                    jPasswordUser.setText("");
                    cmbLevel.setSelectedItem("Admin");
                    }else if(cmbLevel.getSelectedItem().equals("Petugas")){
                        bdataanggota.setEnabled(true);
                        bdatabuku.setEnabled(true);
                        bdatapeminjaman.setEnabled(true);
                        bdatapengembalian.setEnabled(true);
                        Login.setText("Logout");
                        PanelLogin.setVisible(false);
                        jPasswordPass.setText("");
                        jPasswordUser.setText("");
                        cmbLevel.setSelectedItem("Admin");
                    }else if(cmbLevel.getSelectedItem().equals("Administrasi")){
                        bdatapeminjaman.setEnabled(true);
                        bdatapengembalian.setEnabled(true);   
                        Login.setText("Logout");
                        PanelLogin.setVisible(false);
                        jPasswordPass.setText("");
                        jPasswordUser.setText("");
                        cmbLevel.setSelectedItem("Admin");
                    }else if((rs.getRow()==0)){
                    JOptionPane.showMessageDialog(null,"Maaf, "
                            + "Gagal masuk ID Pengguna atau Kata Sandi "
                            + "atau Level Pengguna tidak sesuai ...!");
                    bdataanggota.setEnabled(false);
                    bdatabuku.setEnabled(false);
                    bdatapeminjaman.setEnabled(false);
                    bdatapetugas.setEnabled(false);
                    bdatapengembalian.setEnabled(false);
                    Login.setText("Login");
                }
                   stat.close(); 
                    } 
        
        } catch (SQLException e) {
            System.out.println("Error" +e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
      login a=new login();
        a.setVisible(true);
        dispose();
        if(Login.getText().trim().equals("Logout")){
                    bdataanggota.setEnabled(false);
                    bdatabuku.setEnabled(false);
                    bdatapeminjaman.setEnabled(false);
                    bdatapetugas.setEnabled(false);
                    bdatapengembalian.setEnabled(false);
                    Login.setText("Login");
                    PanelLogin.setVisible(false);
        }else if(Login.getText().trim().equals("Login")){
            PanelLogin.setVisible(true);
            jPasswordUser.requestFocus();
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void bdatapetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdatapetugasActionPerformed
        // TODO add your handling code here:
        petugas as=new petugas();
        as.setVisible(true);
      
    }//GEN-LAST:event_bdatapetugasActionPerformed

    private void bdataanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdataanggotaActionPerformed
        // TODO add your handling code here:
        anggota c=new anggota();
        c.setVisible(true);
       
    }//GEN-LAST:event_bdataanggotaActionPerformed

    private void bdatabukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdatabukuActionPerformed
        // TODO add your handling code here:
        Databuku a=new Databuku();
        a.setVisible(true);
       
    }//GEN-LAST:event_bdatabukuActionPerformed

    private void bdatapeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdatapeminjamanActionPerformed
        // TODO add your handling code here:
        Peminjaman b= new Peminjaman();
        b.setVisible(true);
        
    }//GEN-LAST:event_bdatapeminjamanActionPerformed

    private void bdatapengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdatapengembalianActionPerformed
        // TODO add your handling code here:
        pengembalian sa=new pengembalian();
        sa.setVisible(true);
       
    }//GEN-LAST:event_bdatapengembalianActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
         int a=JOptionPane.showConfirmDialog(null, "Yakin mau Keluar?","",JOptionPane.YES_NO_OPTION);
        if(a==0){
            try {
                System.exit(0);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Login;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JButton bdataanggota;
    private javax.swing.JButton bdatabuku;
    private javax.swing.JButton bdatapeminjaman;
    private javax.swing.JButton bdatapengembalian;
    private javax.swing.JButton bdatapetugas;
    private javax.swing.JComboBox<String> cmbLevel;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jPasswordPass;
    private javax.swing.JTextField jPasswordUser;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JMenu menu;
    // End of variables declaration//GEN-END:variables


}
